spring:
  config:
    activate:
      on-profile: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: url
    username: username
    password: password
    driver-class-name:
    hikari:
      pool-name: qna-mariadb-datasource
      auto-commit: false
      connection-timeout: 3000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 50000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  config: classpath:logback-prod.xml

enable-logging: true



aes:
  secret-key: 4e6f0d8e28d0f2fa74e6c6d8e38a9f6b