spring:
  config:
    activate:
      on-profile: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://127.0.0.1:3306/AI_SH?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: aicc-postgres-datasource
      auto-commit: false
      connection-timeout: 3000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 50000
      max-lifetime: 60000
  jpa:
    properties:
      hibernate:
        default_schema: admin
    hibernate:
      ddl-auto: validate
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mail:
    host: 211.45.62.69
    port: 25
    properties:
      mail:
        smtp:
          auth: false

logging:
  config: classpath:logback-local.xml

aes:
  secret-key: 4e6f0d8e28d0f2fa74e6c6d8e38a9f6b